M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2026-07-13T13:08:40-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-13T13:08:40-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.99Y-2.2137
X4.99Y-4.91
X6.38Y-2.2137
X6.38Y-4.91
M30
